# Generated by Django 5.0.6 on 2024-05-20 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
