name: Django Pipeline

permissions:
  contents: write

on:
  push:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.3]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install django-webpush
    - name: Run Tests
      run: |
        cd waste_watcher
        echo -n "testpass" > password.txt
        python manage.py test
        
  merge-with-production:
    needs: build
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v4
    - name: Run merge
      run: |
        git config --global user.name 'Github Actions Integration'
        git config --global user.email '<>'
        git fetch --unshallow
        git checkout production
        git pull
        git merge --no-ff main -m "Auto-merge main back to production"
        git push
        
    
